name: Expresiones y funciones

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: src/main
    steps:
      - uses: actions/checkout@v3
      - name: expresiones
        run: echo ${{ matrix.configuration }}
        if: ${{ contains(matrix.configuration, "Release") }}
      
      
